/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "rrc_15_3.asn1"
 * 	`asn1c -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ScramblingId_H_
#define	_ScramblingId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ScramblingId */
typedef long	 ScramblingId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ScramblingId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ScramblingId;
asn_struct_free_f ScramblingId_free;
asn_struct_print_f ScramblingId_print;
asn_constr_check_f ScramblingId_constraint;
xer_type_decoder_f ScramblingId_decode_xer;
xer_type_encoder_f ScramblingId_encode_xer;
per_type_decoder_f ScramblingId_decode_uper;
per_type_encoder_f ScramblingId_encode_uper;
per_type_decoder_f ScramblingId_decode_aper;
per_type_encoder_f ScramblingId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ScramblingId_H_ */
#include <asn_internal.h>
