/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "rrc_15_3.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_ServCellIndexRrc_H_
#define	_ServCellIndexRrc_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ServCellIndexRrc */
typedef long	 ServCellIndexRrc_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ServCellIndexRrc_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ServCellIndexRrc;
asn_struct_free_f ServCellIndexRrc_free;
asn_struct_print_f ServCellIndexRrc_print;
asn_constr_check_f ServCellIndexRrc_constraint;
ber_type_decoder_f ServCellIndexRrc_decode_ber;
der_type_encoder_f ServCellIndexRrc_encode_der;
xer_type_decoder_f ServCellIndexRrc_decode_xer;
xer_type_encoder_f ServCellIndexRrc_encode_xer;
per_type_decoder_f ServCellIndexRrc_decode_uper;
per_type_encoder_f ServCellIndexRrc_encode_uper;
per_type_decoder_f ServCellIndexRrc_decode_aper;
per_type_encoder_f ServCellIndexRrc_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServCellIndexRrc_H_ */
#include <asn_internal.h>
